package com.grappim.wayprint.buildlogic

import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.compose.compiler.gradle.ComposeCompilerGradlePluginExtension
import java.io.File

// Opt-in Compose Compiler stability audit — see docs/compose/stability-reports-plan.md.
// Off by default: -PcomposeStabilityReport to generate *-classes.txt / *-composables.txt.
fun Project.configureComposeStabilityReports() {
    if (!project.hasProperty("composeStabilityReport")) return
    extensions.configure<ComposeCompilerGradlePluginExtension> {
        metricsDestination.set(layout.buildDirectory.dir("compose_reports"))
        reportsDestination.set(layout.buildDirectory.dir("compose_reports"))
    }
}

// Trust-lists foreign types the Compose compiler has no marker for but which are genuinely
// immutable (all-`val`), so it stops defaulting them to Unstable — see
// docs/CHECKLIST.md 20.4 and docs/compose/stability-reports.md. Unlike the reports above, this
// changes real generated bytecode on every build, debug and release alike, so it is never gated
// behind -PcomposeStabilityReport.
fun Project.configureComposeStabilityConfig() {
    extensions.configure<ComposeCompilerGradlePluginExtension> {
        // `rootDir` wrapped through `layout.file(Provider<File>)`, not `rootProject.layout...` —
        // the latter reads another project's (":") mutable state, which Isolated Projects forbids.
        stabilityConfigurationFiles.add(
            layout.file(provider { File(rootDir, "config/compose/stability_config.conf") })
        )
    }
}
